package org.oop.exceptions_16;

public class Task346ExceptionsXVIII_Casopis {


}
